export const CHANGE_PLAYER_INFORMATION = 'CHANGE_PLAYER_INFORMATION';
export const SET_UPDATE_SCORE = 'SET_UPDATE_SCORE';
export const RESET_SCORE = 'RESET_SCORE';
export const WILL_PLAY_AGAIN = 'PLAY_AGAIN';
